### PR TITLE
Addition of JSON Dump for consumption as an API

### PR DESCRIPTION
**Pull request by sth2258**

### CODE REVIEW

**Comment by jlboygenius** [comment]
Interesting addition! I've been using the pyVesync tool to pull data and dump it into a JSON format, which I then push into InfluxDB(using Telegraf) and display in Grafana. This addition could make my script a bit easier, because I wouldn't need to do the JSON translation myself.

I'd suggest removing the kwh/watts/minutes/etc text from the data output. For power and voltage, just output a number. This will make it easier for external systems to make use of the data. 

Thanks for all the updates to this awesome tool!

**Comment by sth2258** [comment]
Good idea @jlboygenius - I was on the fence about this, but if it's more than just me using this functionality, happy to oblige 👍 

Done btw

**Comment by webdjoe** [comment]
Thanks for the PR @sth2258.  The json output is a great idea, I'm doing the handling in an external script myself. Chances are this repo will not have any further updates.  I have an [updated branch](https://github.com/markperdue/pyvesync/pull/43) for the dimmable switch and tunable bulb that I am going to merge into the [pyvesync_v2 repo](https://github.com/webdjoe/pyvesync_v2) in the next day or two, time permitting. If you would like to make a PR with that branch, I'll accept and merge it with the new repo.

**Comment by sth2258** [comment]
Hi @webdjoe - Happy to do so, but can you double check that repo? It doesn't have any of the same code in it, and [README](https://github.com/webdjoe/pyvesync_v2/blob/master/README.md) just refers back to here.

**Comment by webdjoe** [comment]
I meant merging your fork with this [updated branch](https://github.com/markperdue/pyvesync/pull/43). I've been trying to tidy up and move it to the other repo but I've been short on time this week.

**Comment by sth2258** [comment]
Closing - moved to [https://github.com/markperdue/pyvesync/pull/45]

**Pull request closed without merging**
