### PR TITLE
Support filter reset for levoit fans

### PR DESCRIPTION
**Pull request by blenk92**
Support resetting the filter to 100% (checked on my core200s)

### CODE REVIEW

**Comment by webdjoe** [comment]
Thank you for the PR, please add a filter_reset feature in the Core 200s features dict and check to function to prevent unsupported devices from making this call.

**Comment by blenk92** [comment]
@webdjoe Thanks for the quick reply. Added the check ;-)

**Comment by blenk92** [comment]
@webdjoe  anything else missing to get this merged?

**Comment by ljmerza** [comment]
I can confirm this works on 300s as well. great job this will help a lot

**Pull request merged**
