### PR TITLE
Support LUH-M101S-WUS (OASISMIST1000S) humidifer

### PR DESCRIPTION
**Pull request by sjafferali**
https://github.com/webdjoe/pyvesync/issues/177

Tested working on my device.

### CODE REVIEW

**Comment by webdjoe** [comment]
Thank you for the PR!! I'm glad you were able to run the tests. I will review & incorporate shortly

**Comment by sjafferali** [comment]
@webdjoe Sure, let me know if any changes are needed.

**Comment by sjafferali** [comment]
@webdjoe Is there any update on this? Please let me know if there is anything I can do to help. I am currently waiting on this in order to add it into the home assistant component. 

Thanks for all your great work on this package!

**Comment by gabino75** [comment]
+1 would love if this got merged. Also need it in order to add it into my home assistant

**Comment by webdjoe** [comment]
Sorry for delay, there was a conflict so I created a new branch to rebase. Merged with #203 and released with version 2.1.10

**Comment by sjafferali** [comment]
Thank you, @webdjoe!

**Comment by gabino75** [comment]
Thanks!!

**Pull request closed without merging**
