### PR TITLE
add support for ESW10-USA

### PR DESCRIPTION
**Pull request by linuxkd**
This PR adds support for the new ESW10-USA outlet, and resolves Issue #61

### CODE REVIEW

**Comment by linuxkd** [comment]
@markperdue @webdjoe Is this project being maintained? I don't see any commits from @markperdue in the past year - on any project. Are you good dude? Would you guys like some help with this?

**Review by webdjoe — APPROVED** [review]

**Comment by webdjoe** [comment]
All PR's and requests are welcome. Sorry for the delay, I missed this one.  Not 'actively' maintained but I'm trying to keep up with bug fixes and issues. I haven't heard from Mark, so not sure what his status is. 

Would you mind making a minor version bump, so I can just build to pypi?

**Comment by martin308** [comment]
FYI I tested this with my `ESW10-USA` outlets and it can query some information about them but it is unable to turn them on and off

**Comment by webdjoe** [comment]
I can't test this without the packets. If you capture and post, I will debug.

**Comment by marks-assistant** [comment]
I have these outlets too and can't get them to work.  If there is new code that needs verified I can do that.

**Pull request closed without merging**
