### PR TITLE
Adjust Current Power and add historical energy reading

### PR DESCRIPTION
**Pull request by webdjoe**
Hi Mark,  You did an amazing job with this script.  I just adjusted the way the current power is calculated.  Instead of using today's energy and dividing by active time, I converted the hex numbers to decimal and divided by 8192.  I found this in another vesync script on github and credited the author.  I also added some functions to return historical energy readings.  Let me know what you think

### CODE REVIEW

**Comment by jlboygenius** [comment]
This is great! I ran into the same problems and was working to apply the same power reporting fix. I guess I should have checked the Pull requests.

**Review by jlboygenius — APPROVED** [review]

**Comment by markperdue** [comment]
Great work on this pr. Sorry for the very delayed merged.

**Comment by jlboygenius** [comment]
Here's another one to check out.
https://github.com/webdjoe/pyvesync_v2

Updates to your library to support the new vesync outlets.

**Comment by markperdue** [comment]
Thanks, I saw that and am glad someone took over the active home assistant implementation to keep things updated with such good additions. Now that there are multiple vesync products I'll look into refactoring this into a vesync platform so that it might integrate more naturally into HA

**Comment by webdjoe** [comment]
Thank you for your code, I couldn't have done anything without it.  I tried to keep you original structure intact to support the component you developed for HA.  It seems with every time they update the app the api calls change and are much more comprehensive.  The server denies requests if they aren't complete.  And they added a uuid for new devices instead of a cid.  I did a PR with HA to change the package for the vesync component and updated the component for vesync wall switches that don't monitor energy. Im working on updating the code for the new api they released with the new version of the app as well as support for the european outlets.  I would love to have your input, I know my code is .... crude to say the least.

**Comment by webdjoe** [comment]
I just made a new branch for supporting EU outlets and refactored the code to the new app api.  I would appreciate it if you had any input-

https://github.com/webdjoe/pyvesync_v2/tree/Dev

**Comment by markperdue** [comment]
> I just made a new branch for supporting EU outlets and refactored the code to the new app api. I would appreciate it if you had any input-
> 
> https://github.com/webdjoe/pyvesync_v2/tree/Dev

Will take a look later this week. I also refactored things a bit on my end in a feature branch. I just received the 15A outlet so I've only added support for that one. The vesync api is a bit of a mess as you mentioned so some assumptions I made early on about how they would grow their api turned out to be wrong so the refactor in the branch tries another approach that might make it easier to maintain going forward.

**Comment by webdjoe** [comment]
I attached an archive with all of the captures for all devices.  I like your solution, I've just starting learning about decorators but I haven't got that far yet.  I'm not sure what version of the app you are running but I updated mine and the whole api changed.  The new api structure doesn't let you make calls that don't have all of the fields in the body.  
I was thinking of a way to capture all the details for each device (voltage, power, energy, etc) in one call and pass them as a list or dictionary to improve the performance instead of having a call for each detail of each device.  The TP Link HA component does it that way. I was wondering if you have any ideas to make that happen?

[VesyncPacketCapture.zip](https://github.com/markperdue/pyvesync/files/2969184/VesyncPacketCapture.zip)

**Comment by markperdue** [comment]
I'm using the latest iphone app and capturing the api calls through a proxy listener. Good idea on the consolidated call - I'll take a stab at that approach and see how it looks

**Comment by markperdue** [comment]
I redid things a bit that should consolidate down the api calls. Now each switch implementation must include an update() method. For the 7a and 15a switches this involves a call to `get_details()` and `get_energy_details()` where `get_details()` makes a single call to the details api relevant for the switch type and `get_energy_details()` makes 3 api calls for weekly, monthly, and yearly data. All the data is then saved to the switch object so items like my_switch.weekly_energy_total() returns the data that would have previously been pulled.

See https://github.com/markperdue/pyvesync/commit/d9c0ed146c08bb27914e956e25f4f94dc0d17b57#diff-3ebf830a771cf749fb3ff9801b8617b3

**Pull request merged**
