### PR TITLE
Add support for Dual 200S humidifier device

### LINKED ISSUE #95: Support for Dual 200S Humidifier
Happy to contribute this (I think I have it working), but wanted to file an issue first for tracking.

API response for `/cloud/v1/deviceManaged/devices`:

```
{'traceId': '1635714379', 'code': 0, 'msg': 'request success', 'result': {'total': 1, 'pageSize': 100, 'pageNo': 1, 'list': [{'deviceRegion': 'US', 'isOwner': True, 'authKey': None, 'deviceName': 'Nursery Humidifier', 'deviceImg': 'https://image.vesync.com/defaultImages/Dual_200S_Series/icon_dual200s_humidifier_160.png', 'cid': 'XXX', 'deviceStatus': 'on', 'connectionStatus': 'online', 'connectionType': 'WiFi+BTOnboarding+BTNotify', 'deviceType': 'Dual200S', 'type': 'wifi-air', 'uuid': 'XXX', 'configModule': 'WiFiBTOnboardingNotify_AirHumidifier_Dual200S_US', 'macID': 'XXX', 'mode': None, 'speed': None, 'extension': None, 'currentFirmVersion': None, 'subDeviceNo': None, 'subDeviceType': None, 'deviceFirstSetupTime': 'Oct 1, 2021 11:27:59 PM'}]}}
```

API response for `/cloud/v2/deviceManaged/bypassV2`:

```
{'traceId': '1635714380', 'code': 0, 'msg': 'request success', 'result': {'traceId': '1635714380', 'code': 0, 'result': {'enabled': True, 'mist_virtual_level': 1, 'mist_level': 1, 'mode': 'auto', 'water_lacks': False, 'water_tank_lifted': False, 'humidity': 54, 'humidity_high': False, 'display': False, 'automatic_stop_reach_target': True, 'configuration': {'auto_target_humidity': 58, 'display': False, 'automatic_stop': True}, 'extension': {'schedule_count': 0, 'timer_remain': 0}}}}
```

Looks identical to the Classic 300S except no `night_light_brightness` field.

### PR DESCRIPTION
**Pull request by bhamiltoncx**
Fixes #95. The Dual 200S humidifer seems identical to the Classic 300S humidifier, except it has no night-light.

Tested with:

```
% cat test.py
import pyvesync

manager = pyvesync.VeSync("XXX", "XXX", "XXX")
manager.login()
manager.update()

manager.fans[0].display()

% /usr/bin/python3 test.py
Device Name:... Nursery Humidifier
Model: ........ Dual200S       
Subdevice No: . None           
Status: ....... on             
Online: ....... online         
Type: ......... wifi-air       
CID: .......... (snip)
UUID: ......... (snip)
Mode: ....................... auto 
Humidity: ................... 54 percent
Mist Virtual Level: ......... 1 
Mist Level: ................. 1 
Water Lacks: ................ False 
Humidity High: .............. False 
Water Tank Lifted: .......... False 
Display: .................... False 
Automatic Stop Reach Target:  True 
Auto Target Humidity: ....... 58 percent
Automatic Stop: ............. True 
```

### CODE REVIEW

**Comment by bhamiltoncx** [comment]
Not sure why the validation build was cancelled — let me know if there's any action I can take there.

**Comment by bhamiltoncx** [comment]
Friendly ping @webdjoe — anything else I can add here?

**Comment by webdjoe** [comment]
Thank you for the PR, do you mind testing? I combined with the 300S class and excluded the night light feature.

**Comment by bhamiltoncx** [comment]
Will do!

**Comment by bhamiltoncx** [comment]
Looks like there's a small typo:

```
>>> manager.update()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/pyvesync-1.4.2-py3.8.egg/pyvesync/vesync.py", line 291, in update
    self.get_devices()
  File "/usr/local/lib/python3.9/site-packages/pyvesync-1.4.2-py3.8.egg/pyvesync/vesync.py", line 240, in get_devices
    proc_return = self.process_devices(device_list)
  File "/usr/local/lib/python3.9/site-packages/pyvesync-1.4.2-py3.8.egg/pyvesync/vesync.py", line 219, in process_devices
    v.append(_device_builder(dev_type, dev, self))
  File "/usr/local/lib/python3.9/site-packages/pyvesync-1.4.2-py3.8.egg/pyvesync/vesync.py", line 73, in _device_builder
    return device_name(config, manager)
  File "/usr/local/lib/python3.9/site-packages/pyvesync-1.4.2-py3.8.egg/pyvesync/vesyncfan.py", line 1073, in __init__
    if 'nightlight' in air_features.get(details.type):
AttributeError: 'dict' object has no attribute 'type'
```

I've pushed a fix to this PR which makes everything work. Thanks, LMK how it looks.

**Comment by webdjoe** [comment]
Great, thank you! Uploading pip package now.

**Comment by bhamiltoncx** [comment]
Wonderful!

**Pull request merged**
