### PR TITLE
Add a Redactor function to the debug output

### PR DESCRIPTION
**Pull request by sdrapha**
To make it easier for debuging issues online

### CODE REVIEW

**Comment by webdjoe** [comment]
@sdrapha Thank you contributing again! Can you rebase this PR with the Cosori #55  PR?

**Comment by sdrapha** [comment]
> @sdrapha Thank you contributing again! Can you rebase this PR with the Cosori #55 PR?

Sure! No problem. I'm away from my computer for a while, but I will try to do it remotely when I get a chance.

**Comment by sdrapha** [comment]
@webdjoe, ready to go.

**Comment by sdrapha** [comment]
Rebased this PR on current master branch

**Pull request merged**
