### PR TITLE
Refactor device adding and configuration

### PR DESCRIPTION
**Pull request by webdjoe**

### CODE REVIEW

**Comment by kevchu3** [comment]
Hi @webdjoe, just had time to take a look and test your `air-refactor` branch now.  I've tested in both the Classic 200S and Dual 200S which essentially have the same supported APIs.  Here were the methods available for the old pyvesync library:

```
$ python3
Python 3.10.2 (main, Jan 17 2022, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyvesync import VeSync
>>> manager = VeSync("USERNAME", "PASSWORD", "US")
>>> manager.login()
True
>>> manager.update()
>>> humidifier = manager.fans[0]
>>> humidifier.
humidifier.automatic_stop_off()         humidifier.current_firm_version         humidifier.extension                    humidifier.set_display(                 humidifier.turn_off_display()
humidifier.automatic_stop_on()          humidifier.details                      humidifier.firmware_update              humidifier.set_humidity(                humidifier.turn_on()
humidifier.build_config_dict(           humidifier.device_image                 humidifier.get_details()                humidifier.set_humidity_mode(           humidifier.turn_on_display()
humidifier.build_humid_dict(            humidifier.device_name                  humidifier.is_on                        humidifier.set_mist_level(              humidifier.type
humidifier.cid                          humidifier.device_status                humidifier.mac_id                       humidifier.set_night_light_brightness(  humidifier.update()
humidifier.config                       humidifier.device_type                  humidifier.manager                      humidifier.speed                        humidifier.uuid
humidifier.config_module                humidifier.display()                    humidifier.mode                         humidifier.sub_device_no                
humidifier.connection_status            humidifier.displayJSON()                humidifier.night_light                  humidifier.toggle_switch(               
humidifier.connection_type              humidifier.enabled                      humidifier.set_automatic_stop(          humidifier.turn_off()                   
```

The new pyvesync library has a few more implemented methods (yay!)
```
>>> humidifier.
humidifier.automatic_stop_off()         humidifier.current_firm_version         humidifier.firmware_update              humidifier.set_display(                 humidifier.turn_on()
humidifier.automatic_stop_on()          humidifier.details                      humidifier.get_details()                humidifier.set_humidity(                humidifier.turn_on_display()
humidifier.build_api_dict(              humidifier.device_image                 humidifier.is_on                        humidifier.set_humidity_mode(           humidifier.type
humidifier.build_config_dict(           humidifier.device_name                  humidifier.mac_id                       humidifier.set_mist_level(              humidifier.update()
humidifier.build_humid_dict(            humidifier.device_status                humidifier.manager                      humidifier.set_night_light_brightness(  humidifier.uuid
humidifier.cid                          humidifier.device_type                  humidifier.mist_levels                  humidifier.set_warm_level(              humidifier.warm_mist_feature
humidifier.config                       humidifier.display()                    humidifier.mist_modes                   humidifier.speed                        humidifier.warm_mist_levels
humidifier.config_dict                  humidifier.displayJSON()                humidifier.mode                         humidifier.sub_device_no                
humidifier.config_module                humidifier.enabled                      humidifier.night_light                  humidifier.toggle_switch(               
humidifier.connection_status            humidifier.extension                    humidifier.set_auto_mode()              humidifier.turn_off()                   
humidifier.connection_type              humidifier.features                     humidifier.set_automatic_stop(          humidifier.turn_off_display()           
```

As a sanity check of my original issue #116, this now works:
```
>>> humidifier.device_status
'on'
>>> humidifier.turn_off()
True
>>> humidifier.device_status
'off'
>>> humidifier.turn_on()
True
>>> humidifier.device_status
'on'
```

I see my humidifier now has a night light brightness implemented as well.  The old one:
```
>>> humidifier.details
{'humidity': 55, 'mist_virtual_level': 2, 'mist_level': 1, 'mode': 'manual', 'water_lacks': False, 'humidity_high': False, 'water_tank_lifted': False, 'display': False, 'automatic_stop_reach_target': False}
```

And the new one:
```
>>> humidifier.details
{'humidity': 55, 'mist_virtual_level': 2, 'mist_level': 1, 'mode': 'manual', 'water_lacks': False, 'humidity_high': False, 'water_tank_lifted': False, 'display': False, 'automatic_stop_reach_target': False, 'night_light_brightness': 0}
```

Hope this helps!

**Comment by webdjoe** [comment]
Thank you @kevchu3! Can you do me a favor and test the mist level method on both of those humidifiers? The mist level should be 1-9 on the classic 200s and low/high on the dual 200s. Please let me know if that isn't correct.

**Review by kevchu3 — COMMENTED** [review]
Reviewing changes per https://github.com/webdjoe/pyvesync/pull/121#issuecomment-1065125437:

I'm getting an error on `set_mist_level()` as well as `set_auto_mode()`, see below:
```
>>> humidifier.set_mist_level(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kechung/Git/pyvesync/src/pyvesync/vesyncfan.py", line 1199, in set_mist_level
    if level not in self.mist_modes:
TypeError: argument of type 'NoneType' is not iterable
>>> humidifier.set_auto_mode()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kechung/Git/pyvesync/src/pyvesync/vesyncfan.py", line 1185, in set_auto_mode
    if 'auto' in self.mist_modes:
TypeError: argument of type 'NoneType' is not iterable
```

Other methods seem to be working fine:
```
>>> humidifier.set_humidity(45)
True
```

**Comment by webdjoe** [comment]
@kevchu3 Thanks for letting me know, fix pushed!

**Review by kevchu3 — COMMENTED** [review]
I did some more testing on the two humidifiers.  To verify whether the methods are actually updating the humidifiers, I'm using the VeSync app on my phone.  For the Classic 200S, `set_mist_level()` and `set_auto_mode()` are working.  However, for the Dual 200S, `set_mist_level('low')` and `set_mist_level('high')` don't appear to be working, and only `set_auto_mode()` is working.

As another bug, I've noticed that `details` and `display()` are not showing the proper `mist_virtual_level`, `mist_level`, or `mode` on either of the two humidifiers.  However, if I run `update()`, it then refreshes the details with the proper humidity.

Some testing notes below on the Classic 200S:
```
>>> humidifier.device_type
'Classic200S'
>>> humidifier.details
{'humidity': 55, 'mist_virtual_level': 2, 'mist_level': 1, 'mode': 'manual', 'water_lacks': False, 'humidity_high': False, 'water_tank_lifted': False, 'display': False, 'automatic_stop_reach_target': False, 'night_light_brightness': 0}
>>> humidifier.mist_levels
[1, 2, 3, 4, 5, 6, 7, 8, 9]
>>> humidifier.set_mist_level(5)
True
>>> humidifier.details
{'humidity': 55, 'mist_virtual_level': 2, 'mist_level': 1, 'mode': 'manual', 'water_lacks': False, 'humidity_high': False, 'water_tank_lifted': False, 'display': False, 'automatic_stop_reach_target': False, 'night_light_brightness': 0}
>>> humidifier.set_mist_level(9)
True
>>> humidifier.details
{'humidity': 55, 'mist_virtual_level': 2, 'mist_level': 1, 'mode': 'manual', 'water_lacks': False, 'humidity_high': False, 'water_tank_lifted': False, 'display': False, 'automatic_stop_reach_target': False, 'night_light_brightness': 0}
>>> humidifier.set_mist_level(2)
True
>>> humidifier.details
{'humidity': 55, 'mist_virtual_level': 2, 'mist_level': 1, 'mode': 'manual', 'water_lacks': False, 'humidity_high': False, 'water_tank_lifted': False, 'display': False, 'automatic_stop_reach_target': False, 'night_light_brightness': 0}
>>> humidifier.set_auto_mode()
True
>>> humidifier.details
{'humidity': 55, 'mist_virtual_level': 2, 'mist_level': 1, 'mode': 'manual', 'water_lacks': False, 'humidity_high': False, 'water_tank_lifted': False, 'display': False, 'automatic_stop_reach_target': False, 'night_light_brightness': 0}
>>> humidifier.set_mist_level(3)
True
>>> humidifier.update()
>>> humidifier.details
{'humidity': 57, 'mist_virtual_level': 3, 'mist_level': 1, 'mode': 'manual', 'water_lacks': False, 'humidity_high': False, 'water_tank_lifted': False, 'display': True, 'automatic_stop_reach_target': False, 'night_light_brightness': 0}
```

And testing notes on the Dual 200S:
```
>>> humidifier.device_type
'Dual200S'
>>> humidifier.mist_levels
['low', 'high']
>>> humidifier.set_mist_level('low')
True
>>> humidifier.details
{'humidity': 44, 'mist_virtual_level': 1, 'mist_level': 1, 'mode': 'manual', 'water_lacks': False, 'humidity_high': False, 'water_tank_lifted': False, 'display': False, 'automatic_stop_reach_target': True}
>>> humidifier.set_mist_level('high')
True
>>> humidifier.details
{'humidity': 44, 'mist_virtual_level': 1, 'mist_level': 1, 'mode': 'manual', 'water_lacks': False, 'humidity_high': False, 'water_tank_lifted': False, 'display': False, 'automatic_stop_reach_target': True}
>>> humidifier.set_mist_level(1)
False
>>> humidifier.set_auto_mode()
True
>>> humidifier.update()
>>> humidifier.details
{'humidity': 47, 'mist_virtual_level': 1, 'mist_level': 1, 'mode': 'auto', 'water_lacks': False, 'humidity_high': False, 'water_tank_lifted': False, 'display': False, 'automatic_stop_reach_target': True}
>>> humidifier.set_mist_level('high')
True
>>> humidifier.update()
>>> humidifier.details
{'humidity': 47, 'mist_virtual_level': 1, 'mist_level': 1, 'mode': 'auto', 'water_lacks': False, 'humidity_high': False, 'water_tank_lifted': False, 'display': False, 'automatic_stop_reach_target': True}
```

**Comment by webdjoe** [comment]
@kevchu3 fixed mist levels to numeric values. Let me know if that works.

Without being able to debug there's no way of knowing why the humidity and mist level values are incorrect. Let me know if you figure anything further out.

**Comment by kevchu3** [comment]
Hi @webdjoe, the Dual 200S mist levels of low and high are working now, but I wanted to check with you if `mist_virtual_level` and `mist_level` are being set in tandem as intended.

I'll start with the Classic 200S humidifier, which was previously working well.  There are 9 mist levels on the VeSync app which correspond to `mist_virtual_level`.  The `mist_level` of 1, 2, and 3 corresponds to low, medium, and high, which are the three colors for manual mode on the physical humidifier itself, and the API behind the scene probably does some rounding calculations to make this so.

Classic 200S testing notes:
```
>>> humidifier.device_type
'Classic200S'
>>> humidifier.mist_levels
[1, 2, 3, 4, 5, 6, 7, 8, 9]
>>> humidifier.set_mist_level(4)
True
>>> humidifier.update()
>>> humidifier.details
{'humidity': 46, 'mist_virtual_level': 4, 'mist_level': 2, 'mode': 'manual', 'water_lacks': False, 'humidity_high': False, 'water_tank_lifted': False, 'display': True, 'automatic_stop_reach_target': False, 'night_light_brightness': 0}
>>> humidifier.set_mist_level(7)
True
>>> humidifier.update()
>>> humidifier.details
{'humidity': 47, 'mist_virtual_level': 7, 'mist_level': 3, 'mode': 'manual', 'water_lacks': False, 'humidity_high': False, 'water_tank_lifted': False, 'display': True, 'automatic_stop_reach_target': False, 'night_light_brightness': 0}
>>> humidifier.set_mist_level(9)
True
>>> humidifier.update()
>>> humidifier.details
{'humidity': 50, 'mist_virtual_level': 9, 'mist_level': 3, 'mode': 'manual', 'water_lacks': False, 'humidity_high': False, 'water_tank_lifted': False, 'display': True, 'automatic_stop_reach_target': False, 'night_light_brightness': 0}
```

Now onto the Dual 200S, `vesyncfan.py` has defined 9 mist levels available: `'mist_levels': list(range(1, 10))`.  However, in reality there are only two: 1 and 2, corresponding to low and high, respectively.  Setting mist levels 3 through 9 will erroneously return True, because there is nothing actually happening in the background and the API is probably rejecting the call.  This is the same case whether we are setting mist level of 3-9 from either a previous value of 1 or 2, it simply will not set it.

The design question is whether we want to keep this as is, or whether we want to restrict the available `mist_levels` to just `[1, 2]`.  If we choose the latter (which I would prefer), then we will need to update some additional code to account for variation between humidifier types.  These lines of code come to mind:
```
logger.debug('Humidifier mist level must be between 0 and 9')
"""Set humidifier mist level with int between 0 - 9."""
```

Dual 200S testing notes:
```
>>> humidifier.device_type
'Dual200S'
>>> humidifier.mist_levels
[1, 2, 3, 4, 5, 6, 7, 8, 9]
>>> humidifier.set_mist_level(1)
True
>>> humidifier.update()
>>> humidifier.details
{'humidity': 41, 'mist_virtual_level': 1, 'mist_level': 1, 'mode': 'manual', 'water_lacks': False, 'humidity_high': False, 'water_tank_lifted': False, 'display': True, 'automatic_stop_reach_target': False}
>>> humidifier.set_mist_level(2)
True
>>> humidifier.update()
>>> humidifier.details
{'humidity': 40, 'mist_virtual_level': 2, 'mist_level': 2, 'mode': 'manual', 'water_lacks': False, 'humidity_high': False, 'water_tank_lifted': False, 'display': True, 'automatic_stop_reach_target': False}
>>> humidifier.set_mist_level(3)
True
>>> humidifier.update()
>>> humidifier.details
{'humidity': 40, 'mist_virtual_level': 2, 'mist_level': 2, 'mode': 'manual', 'water_lacks': False, 'humidity_high': False, 'water_tank_lifted': False, 'display': True, 'automatic_stop_reach_target': False}
>>> humidifier.set_mist_level(9)
True
>>> humidifier.update()
>>> humidifier.details
{'humidity': 40, 'mist_virtual_level': 2, 'mist_level': 2, 'mode': 'manual', 'water_lacks': False, 'humidity_high': False, 'water_tank_lifted': False, 'display': True, 'automatic_stop_reach_target': False}
>>> humidifier.set_auto_mode()
True
>>> humidifier.update()
>>> humidifier.details
{'humidity': 41, 'mist_virtual_level': 1, 'mist_level': 1, 'mode': 'auto', 'water_lacks': False, 'humidity_high': False, 'water_tank_lifted': False, 'display': True, 'automatic_stop_reach_target': False}
```

**Comment by adityapavan18** [comment]
Testing Notes: LV600S humidifier(LUH-A602S-WUS)

> humidifier.display() - Works
> humidifier.turn_off() - Works
> humidifier.is_on - Works
> humidifier.turn_on() - Works
> humidifier.details  & humidifier.display - dont show correct details for current humidity, current mist level & current warm level
> humidifier.mist_mode - doesnt show manual mode -  shows ['humidity', 'sleep']
> humidifier.set_humidity(45) - Works
> humidifier.set_mist_level(2) - Works
> humidifier.set_warm_level(2) - fails with below error
>>2022-03-17 18:47:00,545 - DEBUG - Invalid mode - setLevel
>> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyvesync/vesyncfan.py", line 1171, in set_warm_level
>     head, body = self.build_api_dict('setLevel')
>   File "/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyvesync/vesyncfan.py", line 871, in build_api_dict
>     raise ValueError
> ValueError

**Comment by webdjoe** [comment]
@adityapavan18 Just fixed the warm mist level method. There is technically no manual mode but I created the set_manual_mode() method to set to manual mist with the lowest setting. Please let me know if this fixes it.

**Comment by adityapavan18** [comment]
@webdjoe - set _warm_level is not throwing error now but  it's not updating the changes on the device.

**Comment by webdjoe** [comment]
@adityapavan18 I think that should fix it

**Comment by adityapavan18** [comment]
> @adityapavan18 I think that should fix it
That works now

Manual mode is still not working. I cannot switch to manual mode - Humidity & Sleep work fine. Only thing set_manual_mode() does is set mist level to 1. Cannot switch to manual mode
IMG_51CEAF5ADFB6-1

**Comment by webdjoe** [comment]
@adityapavan18 Do you know what the api call is? I don't have one of these myself to test out

**Pull request merged**
