### PR TITLE
setup.py should not install 'tests' package at top level

### LINKED ISSUE #58: pyvesync-1.{1,2}.0 tries to install a package called `tests` at top level
Hello Mark,

first, I hope you don't mind I included your component for [Home Assistant Gentoo Overlay](https://github.com/onkelbeh/HomeAssistantRepository). I do not use this component myself, but during compile tests I saw that my test script threw an error, because `setup.py` tries to install a package called `tests` at top level.

Also it would be nice if you could add version tags here at Github.

I will send a PR for the top level violation in a few seconds.

For now, I added both versions with a patch: https://github.com/onkelbeh/HomeAssistantRepository/commit/809805063db7c53b6ed360ce5401e14dc2a609a5

Thanks a lot.
 \B.

### PR DESCRIPTION
**Pull request by onkelbeh**
fixes #58

### CODE REVIEW

**Review by webdjoe — CHANGES_REQUESTED** [review]
Can you please bump the patch version so we keep the master up to date?

**Comment by onkelbeh** [comment]
sure, now is: `1.2.1`

**Review by webdjoe — APPROVED** [review]

**Comment by webdjoe** [comment]
Thank you for the fix!

**Comment by onkelbeh** [comment]
Thanks for patching. (Only 48 left).

**Pull request merged**
