### PR TITLE
Add fan to Home Assistant component

### PR DESCRIPTION
**Pull request by zlalanne**
* Implements a Fan Entity for the VeSync Air Purifier
* Speed (low, medium, high) working, on/off working
* Auto mode not working
* No state attributes implemented

### CODE REVIEW

**Comment by zlalanne** [comment]
This is working decently for me in my Home Assistant 0.93.2 installation. One thing I'm having trouble with getting to work is the "auto" mode. The `auto_mode()` API doesn't seem to work for me.

Looking at the source of `mode_toggle` I don't really see where the mode is being used in the request to the API. Maybe that is the culprit.

**Comment by zlalanne** [comment]
Okay updated this with better support for "auto" mode, which needed a fix in the main library and added some state attributes. I think this is a pretty decent implementation if anyone else wants to try it out.

**Comment by zlalanne** [comment]
@markperdue @webdjoe any feedback on this change? I'd like to see this get into the custom component

**Comment by webdjoe** [comment]
@zlalanne the changes look good to me but there was another issue raised https://github.com/markperdue/pyvesync/issues/33#issuecomment-505666878 with the filter life function.  Are you seeing this issue at all?

Also, HA is changing the way integrations are added through the UI config flow.  You can go through the add integration menu in configuration to setup the component.  This is only available for builtin components, so I have to run and build HA from my fork to test.  I incorporated your fan code into that repo.  It is still early and not fully tested but the main functionality works fairly well for me.  If you wouldn't mind testing it out to make sure the fan component is working as it should.  https://github.com/webdjoe/home-assistant/tree/dev/homeassistant/components/vesync

**Review by webdjoe — APPROVED** [review]
@zlalanne Looks good, thanks for the PR!

**Comment by zlalanne** [comment]
Thanks for merging! I haven't had a chance to try out the new integration stuff with your fork.

On another note, `manifest.json` probably needs to be updated so that it uses the latest library code, since I did make a small bugfix to the core library.

**Pull request merged**
